#! /usr/local/bin/bash
# McFagr - Move Changes From Another Git Repository
# Requirements - the repository is already added as a remote, and has been fetched

# Example:
#d-day=1cc376
#current=84cbbf7495a1be965e5cf27deb3f27d1bf415c58
#HEAD=d676322fb00d40ca4bd2a749a0404a07e2388a41 (init)
#../mcfagr/mcfagr d-day..current --exclude content/plugins --exclude .gitignore --edit-file-list
#../mcfagr/mcfagr d-day..current --exclude content/plugins --exclude .gitignore --local-folder-prefix build/cms

POSITIONAL=()
EXCLUDES=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        #-r|--remote) # Maybe don't need this - as it's already added so git knows about the hashes/branches, without needing the name of the remote
        #    REMOTE="$2"
        #    shift; shift
        #    ;;
        -e|--exclude)
            EXCLUDES+=("$2")
            shift; shift
            ;;
        --edit-file-list)
            EDIT_FILE_LIST=1
            shift
            ;;
        --local-folder-prefix)
            LOCAL_FOLDER_PREFIX="$2"
            shift; shift
            ;;
        -*)
            echo "Unknown option: $1"
            exit 1
            ;;
        *)
            POSITIONAL+=("$1") # save it in an array for later
            shift # past argument
            ;;
    esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters
COMMITISH="$1"

tmpFolder=$(mktemp -d)
filelist="$tmpFolder/filelist"

# Get the list of files that have been changed based on a range of commits that are important, and --exclude <file> criterion
if [[ -z $EXCLUDES ]]; then
    git diff $COMMITISH --numstat > "$filelist"
else
    function addExcludes { printf "'%s' " "${@/#/:(exclude)}"; }
    excludesCmd="$(addExcludes "${EXCLUDES[@]}")"
    bash -c "$(echo git diff $COMMITISH --numstat -- . "$excludesCmd" \> "$filelist")"
fi

# Manually edit the file list
if [[ -n $EDIT_FILE_LIST ]]; then
    [[ -n $VISUAL ]] && $VISUAL "$filelist"
    read -n 1 -p "Pausing... Click any key to continue after editing $filelist" _
fi

# Trim the filelist to only the files
cat "$filelist" | cut -f 3- > "$filelist-without-diff-numbers"
mv "$filelist"{-without-diff-numbers,}

# Calculate the closest commit for each file from the ancestory
difflist="$tmpFolder/difflist"
echo "$difflist"
mostRecentCommit=$(git rev-list -1 $COMMITISH)
while IFS='' read -r file || [[ -n "$file"  ]]; do
    closestCommit=$mostRecentCommit
    numberOfChangesInClosestCommit=99999999999999
    for commit in $(git rev-list $mostRecentCommit); do
        changes=$(git diff init${LOCAL_FOLDER_PREFIX/#/:} $commit --numstat --ignore-all-space -- "$file")
        numberOfChanges=$(printf %s\\n "$changes" | awk '{print $1+$2}' )

        if [ $numberOfChanges -lt $numberOfChangesInClosestCommit ]; then
            numberOfChangesInClosestCommit=$numberOfChanges
            closestCommit=$commit
        fi
    done
    distance=$(git rev-list $closestCommit..$mostRecentCommit | wc -l)
    printf 'commit: %s, distance: %s, number of changes: %s, file: %s\n' $closestCommit $distance $numberOfChangesInClosestCommit $file >> "$difflist"
done < "$filelist"

echo "$difflist"
read -n 1 -p "End" _

# From the given initial change point (different range):
# Actually, not needed - take the oldest commit that is in the 'closest' list
# For each commit
# Check if any files in the to-include list show this as the 'closest' commit
# Do a separate diff and merge to these files, add and commit
# Add these files to the included list
# Create a patch for only the files that are in the included list
# Apply patch
# Resolve possible conflicts with --rerere
# Loop
